package chain

import (
	"bufio"
	"net"
	"net/http"
)

// responseWriter wraps http.ResponseWriter and tracks response status and size.
// It implements http.Flusher, http.Hijacker, and http.Pusher by delegating to
// the underlying ResponseWriter when supported.
//
// It also captures responses generated by the ServeMux itself (404, 405, and
// trailing-slash redirects) so that Mux.ServeHTTP can replay them through the
// root middleware chain and any custom error handlers. See Mux.ServeHTTP.
type responseWriter struct {
	http.ResponseWriter
	status  int
	size    int
	written bool

	// capturing is set by Mux.ServeHTTP while the ServeMux is dispatching and
	// cleared as soon as a registered handler (and its middleware) is entered.
	// Any response written while it is set came from the ServeMux itself
	// rather than from user code.
	capturing bool

	// captured holds the status of a ServeMux-generated response that has been
	// intercepted and not yet sent. capturedBody holds the body bytes the
	// ServeMux wrote for it.
	captured     int
	capturedBody []byte
}

// Compile-time interface checks
var (
	_ http.ResponseWriter = (*responseWriter)(nil)
	_ http.Flusher        = (*responseWriter)(nil)
	_ http.Hijacker       = (*responseWriter)(nil)
	_ http.Pusher         = (*responseWriter)(nil)
	_ ResponseWriter      = (*responseWriter)(nil)
)

// Status returns the HTTP status code of the response. If not yet written, it returns 200 OK.
func (rw *responseWriter) Status() int {
	if rw.status == 0 {
		return http.StatusOK
	}
	return rw.status
}

// Size returns the number of bytes written to the response.
func (rw *responseWriter) Size() int {
	return rw.size
}

// Written returns whether the response has been written to.
func (rw *responseWriter) Written() bool {
	return rw.written
}

// WriteHeader sends an HTTP response header with the provided status code.
//
// Informational (1xx) status codes other than 101 are passed straight through
// and do not finalise the response, matching net/http's own behaviour, so a
// handler may send 103 Early Hints and still set the final status afterwards.
func (rw *responseWriter) WriteHeader(status int) {
	informational := status >= 100 && status <= 199 && status != http.StatusSwitchingProtocols
	if rw.capturing {
		// The ServeMux is answering this request itself (404, 405 or redirect).
		// Capture the first final status so Mux.ServeHTTP can replay it through
		// the middleware chain. Nothing reaches the underlying writer meanwhile.
		if !informational && rw.captured == 0 {
			rw.captured = status
		}
		return
	}
	if informational {
		rw.ResponseWriter.WriteHeader(status)
		return
	}
	if rw.written {
		return
	}
	rw.status = status
	rw.written = true
	rw.ResponseWriter.WriteHeader(status)
}

// Write writes the data to the connection as part of an HTTP reply.
func (rw *responseWriter) Write(b []byte) (int, error) {
	if rw.capturing {
		if rw.captured == 0 {
			rw.captured = http.StatusOK // implicit, as net/http would send
		}
		rw.capturedBody = append(rw.capturedBody, b...)
		return len(b), nil
	}
	if !rw.written {
		rw.written = true
		rw.status = http.StatusOK
	}
	size, err := rw.ResponseWriter.Write(b)
	rw.size += size
	return size, err
}

// Unwrap returns the underlying http.ResponseWriter.
// This enables http.ResponseController to access the original ResponseWriter.
func (rw *responseWriter) Unwrap() http.ResponseWriter {
	return rw.ResponseWriter
}

// Flush implements http.Flusher.
// Sends any buffered data to the client. A successful flush sends the headers,
// so the response is marked as written with the default 200 status if no
// status has been set yet.
func (rw *responseWriter) Flush() {
	if rw.capturing {
		return // nothing has been sent, so there is nothing to flush
	}
	if err := http.NewResponseController(rw.ResponseWriter).Flush(); err != nil {
		return
	}
	if !rw.written {
		rw.written = true
		rw.status = http.StatusOK
	}
}

// Hijack implements http.Hijacker.
// Allows the caller to take over the connection. After a successful hijack the
// response is marked as written, since nothing further can be sent through it.
func (rw *responseWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	conn, buf, err := http.NewResponseController(rw.ResponseWriter).Hijack()
	if err == nil {
		rw.written = true
	}
	return conn, buf, err
}

// Push implements http.Pusher.
// Initiates an HTTP/2 server push.
func (rw *responseWriter) Push(target string, opts *http.PushOptions) error {
	pusher, ok := rw.ResponseWriter.(http.Pusher)
	if !ok {
		return http.ErrNotSupported
	}
	return pusher.Push(target, opts)
}

// wrapResponseWriter wraps an http.ResponseWriter.
func wrapResponseWriter(w http.ResponseWriter) *responseWriter {
	return &responseWriter{ResponseWriter: w}
}
